# Generated by Django 6.0.6 on 2026-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
         migrations.AddField(
             model_name='project',
             name='deadline',
             field=models.DateTimeField(blank=True, null=True),
        ),
    ]