# Generated by Django 6.0.6 on 2026-06-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_project_deadline'),
    ]

    operations = [
         migrations.AddField(
              model_name='employee',
              name='email',
              field=models.CharField(max_length=100, blank=True),
        ),
    ]