# Generated by Django 6.0.6 on 2026-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(max_length=100, blank=True),
        ),
    ]